version: '3.8'

networks:
  apache-php81-mysql-rabbit-api:

services:
  web:
    build: ./etc/docker/php_apache
    tty: true
    hostname: api-app.loc
    container_name: api-app.loc
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./etc/docker/php_apache/php.ini:/usr/local/etc/php/php.ini
    links:
      - mysql-db
      - rabbit
    ports:
      - "8080:80"

  mysql-db:
    image: mysql:5.7
    hostname: api-app-db.loc
    container_name: api-app-db.loc
    working_dir: /application
    volumes:
      - .:/application
    command: --init-file /application/etc/docker/mysql/databases.sql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    hostname: api-app-pma.loc
    container_name: api-app-pma.loc
    volumes:
      - /sessions
    environment:
      PMA_HOST: api-app-db.loc
      PMA_PORT: 3306
    ports:
      - "8081:80"

  rabbit:
    hostname: api-app-rabbitmq.loc
    container_name: api-app-rabbitmq.loc
    image: rabbitmq:3.9-management
    environment:
      - RABBITMQ_DEFAULT_USR=root
      - RABBITMQ_DEFAULT_PASS=root
    expose:
      - "5672"
      - "15672"
    ports:
      - "5672:5672"
      - "15672:15672"
